CC = gcc

all:
	-gcc hw0201.c -o hw0201
	-gcc -g hw0202.c -o  hw0202
	-gcc -g hw0203.c -o  hw0203
	-gcc -g hw0204.c -o hw0204 -lm
	# -gcc -g hw0105.c -o hw0105

clean:
	rm -f hw020{1..4} hw020{1..4}.o *.o