CC = gcc

all:
	-gcc hw0201.c -o hw0201
	-gcc -g hw0202.c -o  hw0202
	# -gcc -g -c hw0103.c mychain.c
	# -gcc hw0103.o mychain.o -o hw0103
	-gcc hw0204.c -o hw0204 -lm
	# -gcc -g hw0105.c -o hw0105

clean:
	rm -f hw020{1..4} hw020{1..4}.o *.o